prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix won: <https://w3id.org/won/core#>
select ?atom ?targetAtom ?connection ?state ?rated ?ratingProperty ?ratingValue where {
	?atom won:connections/rdfs:member ?connection.
    ?connection won:targetAtom ?targetAtom.
  	optional {
      ?connection won:atomState ?state.
    }
  	optional {
      ?connection won:feedbackEvent ?event.
      ?event won:feedback ?feedback.
      ?feedback won:forResource ?rated;
                ?ratingProperty ?ratingValue.
      filter (?rated != ?ratingValue)
    }
}
